pipeline {
    agent any

		parameters {
			string(name: GIT_REPO, description: 'Git repository', trim: true)
			string(name: GIT_BRANCH, description: 'Git branch', trim: true)
		}

    stages {
        stage('init') {
            steps {
								sh 'ls'
								git branch: "${params.GIT_BRANCH}", url: "${params.GIT_REPO}"
            }
        }
				stage('terraform') {
					steps {
						dir('helloworld') {
							sh 'terraform init'
							sh 'terraform plan'
						}
					}
				}
    }

		post {
			cleanup {
				cleanWs()
			}
		}
}
