pipeline {
    agent any
		triggers {
			GenericTrigger(
				genericVariables: [
					[key: 'ref', value: '$.ref']
				],

				causeString: 'Triggered on $ref',

				token: 'abc123',
				tokenCredentialId: '',

				printContributedVariables: true,
				printPostContent: true,

				silentResponse: false,

				regexpFilterText: '$ref',
				regexpFilterExpression: 'refs/heads/' + BRANCH_NAME
			)
		}
		
    stages {
        stage('init') {
            steps {
								sh 'ls'
								// git branch: 'pipeline', url: 'https://github.com/jackproudfoot-end/terraform-jenkins-test.git'
            }
        }
				stage('terraform') {
					steps {
						dir('helloworld') {
							sh 'terraform init'
							sh 'terraform plan'
						}
					}
				}
    }

		post {
			cleanup {
				cleanWs()
			}
		}
}
